[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"

# [[mgr.prepend_keymap]]
# on   = [":"]
# run  = 'shell --silent "/Users/oscar/.config/yazi/toggle_shell.sh"'
# desc = "Open or switch to a shell in a new Wezterm split"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = [ ";" ]
run = 'plugin custom-shell -- auto --interactive --wait'
desc = "custom-shell as default"

[[mgr.prepend_keymap]]
on = [ ":" ]
run = 'plugin custom-shell zsh --block'
desc = "custom-shell as default, interactive, block"
